spring.application.name=cartelera-backend

server.port=8080

#Configuracion H2 Database (persistencia en ./data folder)
spring.datasource.url=jdbc:h2:file:./data/cartelera_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#H2 Console (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#JPA/Hibernate ddl auto para crear y actualizar las tablas automaticamente
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true

#Fotos e imagenes cargadas
file.upload-dir=./uploads
